name = "All The Mons Takes Off"
author = "yarnobachmann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84af5fa3d0f674022d3425d5f8de9ee70fd6c54a2763bb03dd8e73ac08f33ee0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
