name = "All The Mons Takes Off"
author = "yarnobachmann"
version = "1.0.0-rc.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab351775a90ca7409fa76a5822f5e57dd035afe6130930c47eb202a4ffee0100"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
