ServerEvents.generateData('last', allthemons => {

  // DO NOT DELETE THIS
  // let monsToFilter = [
  // "articuno", "mew", "mewtwo", "moltres", "zapdos", "celebi", "entei", "hooh", "lugia", "raikou", "suicune",
  // "deoxys", "groudon", "jirachi", "kyogre", "latias", "latios", "rayquaza", "regice", "regirock", "registeel",
  // "arceus", "azelf", "cresselia", "darkrai", "dialga", "giratina", "heatran", "manaphy", "mesprit", "palkia",
  // "phione", "regigigas", "shaymin", "uxie", "cobalion", "genesect", "keldeo", "kyurem", "landorus", "meloetta",
  // "reshiram", "terrakion", "thundurus", "tornadus", "victini", "virizion", "zekrom", "diancie", "hoopa",
  // "volcanion", "xerneas", "yveltal", "zygarde", "blacephalon", "buzzwole", "celesteela", "cosmoem", "cosmog",
  // "guzzlord", "kartana", "lunala", "magearna", "marshadow", "naganadel", "necrozma", "nihilego", "pheromosa",
  // "poipole", "silvally", "solgaleo", "stakataka", "tapubulu", "tapufini", "tapukoko", "tapulele", "typenull",
  // "xurkitree", "zeraora", "melmetal", "meltan", "calyrex", "eternatus", "glastrier", "kubfu", "regidrago",
  // "regieleki", "spectrier", "urshifu", "zacian", "zamazenta", "zarude", "enamorus", "brutebonnet", "chienpao",
  // "chiyu", "fezandipiti", "fluttermane", "gougingfire", "greattusk", "ironboulder", "ironbundle", "ironcrown",
  // "ironhands", "ironjugulis", "ironleaves", "ironmoth", "ironthorns", "irontreads", "ironvaliant", "koraidon",
  // "miraidon", "munkidori", "ogerpon", "okidogi", "pecharunt", "ragingbolt", "roaringmoon", "sandyshocks",
  // "screamtail", "slitherwing", "terapagos", "tinglu", "walkingwake", "wochien"
  // ]

  let paths = [
    'legendary_spawns_ccc:spawn_pool_world/0144_articuno.json',
    'legendary_spawns_ccc:spawn_pool_world/0145_zapdos.json',
    'legendary_spawns_ccc:spawn_pool_world/0146_moltres.json',
    'legendary_spawns_ccc:spawn_pool_world/0150_mewtwo.json',
    'legendary_spawns_ccc:spawn_pool_world/0151_mew.json',
    'legendary_spawns_ccc:spawn_pool_world/0243_raikou.json',
    'legendary_spawns_ccc:spawn_pool_world/0244_entei.json',
    'legendary_spawns_ccc:spawn_pool_world/0245_suicune.json',
    'legendary_spawns_ccc:spawn_pool_world/0249_lugia.json',
    'legendary_spawns_ccc:spawn_pool_world/0249_lugia_shadow.json',
    'legendary_spawns_ccc:spawn_pool_world/0250_hooh.json',
    'legendary_spawns_ccc:spawn_pool_world/0251_celebi.json',
    'legendary_spawns_ccc:spawn_pool_world/0377_regirock.json',
    'legendary_spawns_ccc:spawn_pool_world/0378_regice.json',
    'legendary_spawns_ccc:spawn_pool_world/0379_registeel.json',
    'legendary_spawns_ccc:spawn_pool_world/0380_latias.json',
    'legendary_spawns_ccc:spawn_pool_world/0381_latios.json',
    'legendary_spawns_ccc:spawn_pool_world/0382_kyogre.json',
    'legendary_spawns_ccc:spawn_pool_world/0383_groudon.json',
    'legendary_spawns_ccc:spawn_pool_world/0384_rayquaza.json',
    'legendary_spawns_ccc:spawn_pool_world/0385_jirachi.json',
    'legendary_spawns_ccc:spawn_pool_world/0386_deoxys.json',
    'legendary_spawns_ccc:spawn_pool_world/0480_uxie.json',
    'legendary_spawns_ccc:spawn_pool_world/0481_mesprit.json',
    'legendary_spawns_ccc:spawn_pool_world/0482_azelf.json',
    'legendary_spawns_ccc:spawn_pool_world/0483_dialga.json',
    'legendary_spawns_ccc:spawn_pool_world/0484_palkia.json',
    'legendary_spawns_ccc:spawn_pool_world/0485_heatran.json',
    'legendary_spawns_ccc:spawn_pool_world/0486_regigigas.json',
    'legendary_spawns_ccc:spawn_pool_world/0487_giratina.json',
    'legendary_spawns_ccc:spawn_pool_world/0488_cresselia.json',
    'legendary_spawns_ccc:spawn_pool_world/0489_phione.json',
    'legendary_spawns_ccc:spawn_pool_world/0490_manaphy.json',
    'legendary_spawns_ccc:spawn_pool_world/0491_darkrai.json',
    'legendary_spawns_ccc:spawn_pool_world/0492_shaymin.json',
    'legendary_spawns_ccc:spawn_pool_world/0493_arceus.json',
    'legendary_spawns_ccc:spawn_pool_world/0494_victini.json',
    'legendary_spawns_ccc:spawn_pool_world/0638_cobalion.json',
    'legendary_spawns_ccc:spawn_pool_world/0639_terrakion.json',
    'legendary_spawns_ccc:spawn_pool_world/0640_virizion.json',
    'legendary_spawns_ccc:spawn_pool_world/0641_tornadus.json',
    'legendary_spawns_ccc:spawn_pool_world/0642_thundurus.json',
    'legendary_spawns_ccc:spawn_pool_world/0643_reshiram.json',
    'legendary_spawns_ccc:spawn_pool_world/0644_zekrom.json',
    'legendary_spawns_ccc:spawn_pool_world/0645_landorus.json',
    'legendary_spawns_ccc:spawn_pool_world/0646_kyurem.json',
    'legendary_spawns_ccc:spawn_pool_world/0647_keldeo.json',
    'legendary_spawns_ccc:spawn_pool_world/0648_meloetta.json',
    'legendary_spawns_ccc:spawn_pool_world/0649_genesect.json',
    'legendary_spawns_ccc:spawn_pool_world/0716_xerneas.json',
    'legendary_spawns_ccc:spawn_pool_world/0717_yveltal.json',
    'legendary_spawns_ccc:spawn_pool_world/0718_zygarde.json',
    'legendary_spawns_ccc:spawn_pool_world/0719_diancie.json',
    'legendary_spawns_ccc:spawn_pool_world/0720_hoopa.json',
    'legendary_spawns_ccc:spawn_pool_world/0721_volcanion.json',
    'legendary_spawns_ccc:spawn_pool_world/0772_typenull.json',
    'legendary_spawns_ccc:spawn_pool_world/0785_tapukoko.json',
    'legendary_spawns_ccc:spawn_pool_world/0786_tapulele.json',
    'legendary_spawns_ccc:spawn_pool_world/0787_tapubulu.json',
    'legendary_spawns_ccc:spawn_pool_world/0788_tapufini.json',
    'legendary_spawns_ccc:spawn_pool_world/0789_cosmog.json',
    'legendary_spawns_ccc:spawn_pool_world/0791_solgaleo.json',
    'legendary_spawns_ccc:spawn_pool_world/0792_lunala.json',
    'legendary_spawns_ccc:spawn_pool_world/0800_necrozma.json',
    'legendary_spawns_ccc:spawn_pool_world/0801_magearna.json',
    'legendary_spawns_ccc:spawn_pool_world/0802_marshadow.json',
    'legendary_spawns_ccc:spawn_pool_world/0807_zeraora.json',
    'legendary_spawns_ccc:spawn_pool_world/0808_meltan.json',
    'legendary_spawns_ccc:spawn_pool_world/0888_zacian.json',
    'legendary_spawns_ccc:spawn_pool_world/0889_zamazenta.json',
    'legendary_spawns_ccc:spawn_pool_world/0890_eternatus.json',
    'legendary_spawns_ccc:spawn_pool_world/0891_kubfu.json',
    'legendary_spawns_ccc:spawn_pool_world/0893_zarude.json',
    'legendary_spawns_ccc:spawn_pool_world/0894_regieleki.json',
    'legendary_spawns_ccc:spawn_pool_world/0895_regidrago.json',
    'legendary_spawns_ccc:spawn_pool_world/0896_glastrier.json',
    'legendary_spawns_ccc:spawn_pool_world/0897_spectrier.json',
    'legendary_spawns_ccc:spawn_pool_world/0898_calyrex.json',
    'legendary_spawns_ccc:spawn_pool_world/0905_enamorus.json',
    'legendary_spawns_ccc:spawn_pool_world/1001_wochien.json',
    'legendary_spawns_ccc:spawn_pool_world/1002_chienpao.json',
    'legendary_spawns_ccc:spawn_pool_world/1003_tinglu.json',
    'legendary_spawns_ccc:spawn_pool_world/1004_chiyu.json',
    'legendary_spawns_ccc:spawn_pool_world/1007_koraidon.json',
    'legendary_spawns_ccc:spawn_pool_world/1008_miraidon.json',
    'legendary_spawns_ccc:spawn_pool_world/1014_okidogi.json',
    'legendary_spawns_ccc:spawn_pool_world/1015_munkidori.json',
    'legendary_spawns_ccc:spawn_pool_world/1016_fezandipiti.json',
    'legendary_spawns_ccc:spawn_pool_world/1017_ogerpon.json',
    'legendary_spawns_ccc:spawn_pool_world/1024_terapagos.json',
    'legendary_spawns_ccc:spawn_pool_world/1025_pecharunt.json',
    'paradox_spawns_ccc:spawn_pool_world/0984_greattusk_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0985_screamtail_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0986_brutebonnet_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0987_fluttermane_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0988_slitherwing_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0989_sandyshocks_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0990_irontreads_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0991_ironbundle_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0992_ironhands_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0993_ironjugulis_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0994_ironmoth_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/0995_ironthorns_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1005_roaringmoon_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1006_ironvaliant_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1009_walkingwake_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1010_ironleaves_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1020_gougingfire_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1021_ragingbolt_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1022_ironboulder_ccc.json',
    'paradox_spawns_ccc:spawn_pool_world/1023_ironcrown_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0793_nihilego_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0794_buzzwole_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0795_pheromosa_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0796_xurkitree_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0797_celesteela_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0798_kartana_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0799_guzzlord_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0803_poipole_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0805_stakataka_ccc.json',
    'ub_spawns_ccc:spawn_pool_world/0806_blacephalon_ccc.json'
  ]

  paths.forEach((path) => {
    allthemons.json(path, {
      "enabled": true,
      "neededInstalledMods": [],
      "neededUninstalledMods": [],
      "spawns": []
    })
  })

})